#!/usr/bin/env bash
#  ╔═╗╔═╗╔═╗╔═╗  ╦  ╔═╗╦ ╦╔╗╔╔═╗╦ ╦╔═╗╦═╗
#  ╠═╣╠═╝╠═╝╚═╗  ║  ╠═╣║ ║║║║║  ╠═╣║╣ ╠╦╝
#  ╩ ╩╩  ╩  ╚═╝  ╩═╝╩ ╩╚═╝╝╚╝╚═╝╩ ╩╚═╝╩╚═
#	Script to control apps launcher
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

# From here you can control your favorite applications for all themes.

case "$1" in
--menu)
	rofi -show drun \
		-theme $HOME/.config/bspwm/rices/$RICETHEME/launcher.rasi &
	disown
	;;
--rice)
	RiceSelector &
	disown
	;;
--terminal)
	kitty &
	disown
	;;
--floating)
	kitty --class FloaTerm,Alacritty &
	disown
	;;
--update)
	kitty --hold --class FloaTerm,Alacritty -e Updates --update-system &
	disown
	;;
--checkupdates)
	kitty --hold --class Updating,Alacritty -e Updates --print-updates &
	disown
	;;
--ranger)
	kitty --class Ranger,Alacritty -e ranger &
	disown
	;;
--nvim)
	kitty -e nvim &
	disown
	;;
--music)
	kitty --class MusicPlayer,Alacritty -e ncmpcpp &
	disown
	;;
--fetch)
	kitty --hold --class Sysfetch,Alacritty -e ~/.local/bin/sysfetch &
	disown
	;;
#Apps
--filemanager)
	thunar &
	disown
	;;
--browser)
	firefox &
	disown
	;;
--editor)
	geany &
	disown
	;;
--telegram)
	telegram &
	disown
	;;
--whats)
	whatsapp-nativefier --disable-gpu &
	disown
	;;
--soundcontrol)
	pavucontrol &
	disown
	;;
*)
	echo "Opción no válida"
	;;
esac
